# Generated by Django 3.1.2 on 2020-10-26 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='content',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (1, '3'), (1, '4'), (1, '5'), (1, '6'), (1, '7'), (1, '8'), (1, '9'), (1, '10')]),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='design',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (1, '3'), (1, '4'), (1, '5'), (1, '6'), (1, '7'), (1, '8'), (1, '9'), (1, '10')]),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='usability',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (1, '3'), (1, '4'), (1, '5'), (1, '6'), (1, '7'), (1, '8'), (1, '9'), (1, '10')]),
        ),
    ]
