# Generated by Django 3.1.2 on 2020-10-26 13:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201024_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='facebook_u',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='github_u',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='instagram_u',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='linkedin_u',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='twiter_u',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
